### ISSUE TITLE
Configure PVC to use for Spark and Flink applications

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow#710]
WIP.

Right now the storage class used for persistent volumes is set during install of Cloudflow.
The operator creates 1 or more persistent volume claims of 15G respectively for apps using Spark and / or Flink.

It would be better if users can specify their PVC in the config file (and remove the default PVC since it is impossible to choose a default that works for everyone). Once this is changed, the install does not need to know about a storage class, which makes the installation more modular.

UX change will be that an app that needs PVCs will not get deployed if there is no PVC specified. (maybe we can support this in both the blueprint and the config file as override)

**Comment by franciscolopezsancho** [comment]
I'm proposing as an input: 
```
kubernetes.pods.pod {
	volumes {
        foo {
          pvc {
            name = myclaim
          }
        }
      }

      containers.container {
        volume-mounts {
          name = foo
          mountPath = "/var/www/html"
          readOnly = true
        }
}
```


and output:
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: doesntmatter
      image: someimage
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
```
